# Generated by Django 2.0.4 on 2018-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=256)),
                ('client_id', models.CharField(max_length=256)),
                ('token_url', models.CharField(max_length=1024)),
                ('refresh_url', models.CharField(max_length=1024)),
            ],
        ),
    ]
