# Generated by Django 2.0.4 on 2018-04-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='authorize_url',
            field=models.CharField(default='test', max_length=1024),
            preserve_default=False,
        ),
    ]
