# Generated by Django 2.0.4 on 2018-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_authorize_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='revoke_url',
            field=models.CharField(default='test', max_length=1024),
            preserve_default=False,
        ),
    ]
