# Generated by Django 2.0.4 on 2018-04-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_revoke_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='base_api_url',
            field=models.CharField(default='test', max_length=1024),
            preserve_default=False,
        ),
    ]
